name: build

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            platform: macos
          - os: windows-latest
            platform: windows

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn run lint

      - name: Compile Webpack
        run: yarn run compile

      - name: Prepare for release (common)
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          echo '::set-env name=GH_TOKEN::'${{ secrets.github_token }}

      - name: Download latest putio-sync binary
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: yarn run downloadBinary

      - name: Prepare for release (MacOS)
        if: ${{ startsWith(github.ref, 'refs/tags/v') && startsWith(matrix.os, 'macos') }}
        run: |
          # for signing
          echo '::set-env name=CSC_LINK::'${{ secrets.mac_certs }}
          echo '::set-env name=CSC_KEY_PASSWORD::'${{ secrets.mac_certs_password }}

          # for notarization
          echo '::set-env name=API_KEY_ID::'${{ secrets.api_key_id }}
          echo '::set-env name=API_KEY_ISSUER_ID::'${{ secrets.api_key_issuer_id }}
          mkdir -p ~/private_keys/ && echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8

      - name: Build and release Electron app
        run: yarn run electron-builder --${{ matrix.platform }} --publish onTag -c.extraMetadata.version=$(echo ${{ github.ref }} | cut -d / -f 3 | tr -d v)
